namespace VpnSDK.Private.WFP.Interop;

internal enum FWP_DATA_TYPE
{
	FWP_EMPTY = 0,
	FWP_UINT8 = 1,
	FWP_UINT16 = 2,
	FWP_UINT32 = 3,
	FWP_UINT64 = 4,
	FWP_INT8 = 5,
	FWP_INT16 = 6,
	FWP_INT32 = 7,
	FWP_INT64 = 8,
	FWP_FLOAT = 9,
	FWP_DOUBLE = 10,
	FWP_BYTE_ARRAY16_TYPE = 11,
	FWP_BYTE_BLOB_TYPE = 12,
	FWP_SID = 13,
	FWP_SECURITY_DESCRIPTOR_TYPE = 14,
	FWP_TOKEN_INFORMATION_TYPE = 15,
	FWP_TOKEN_ACCESS_INFORMATION_TYPE = 16,
	FWP_UNICODE_STRING_TYPE = 17,
	FWP_BYTE_ARRAY6_TYPE = 18,
	FWP_SINGLE_DATA_TYPE_MAX = 255,
	FWP_V4_ADDR_MASK = 256,
	FWP_V6_ADDR_MASK = 257,
	FWP_RANGE_TYPE = 258,
	FWP_DATA_TYPE_MAX = 259
}
