<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VpnSDK.DnsResolver</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ARSoft.Tools.Net">
      <HintPath>extracted/PFiles64/FastVPN/ARSoft.Tools.Net.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>extracted/PFiles64/FastVPN/Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="VpnSDK.Common">
      <HintPath>extracted/PFiles64/FastVPN/VpnSDK.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>