-- ==============================================================================
-- NEXTAI VPN PLATFORM - SAAS ENTERPRISE DATABASE SCHEMA (V2.1)
-- Database: SQLite / PostgreSQL / MySQL Compatible
-- Tables: Users, Subscriptions, Licenses, Devices (HWID Binding), Billing, Partners, Affiliates, Audits
-- ==============================================================================

-- 1. Users & Accounts
CREATE TABLE IF NOT EXISTS saas_users (
    id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(128),
    role VARCHAR(32) DEFAULT 'USER', -- USER, RESELLER, AFFILIATE, ADMIN, SUPERADMIN
    tier VARCHAR(32) DEFAULT 'FREE', -- FREE, PRO_1PC_1MOB, TEAM_5SEATS, RESIDENTIAL_VIP
    status VARCHAR(32) DEFAULT 'ACTIVE', -- ACTIVE, SUSPENDED, BANNED, EXPIRED
    daily_quota_mb INTEGER DEFAULT 300,
    used_quota_mb REAL DEFAULT 0,
    referred_by VARCHAR(64), -- Affiliate or Reseller ID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Subscriptions & Plans
CREATE TABLE IF NOT EXISTS saas_subscriptions (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    plan_code VARCHAR(64) NOT NULL, -- PLAN_FREE, PLAN_PRO_MONTHLY, PLAN_PRO_YEARLY, PLAN_RESIDENTIAL_VIP
    plan_name VARCHAR(128) NOT NULL,
    max_pc_devices INTEGER DEFAULT 1, -- Default: Max 1 PC
    max_mobile_devices INTEGER DEFAULT 1, -- Default: Max 1 Mobile
    bandwidth_limit_gb REAL DEFAULT 0, -- 0 = Unlimited
    price_usd REAL DEFAULT 0,
    status VARCHAR(32) DEFAULT 'ACTIVE', -- ACTIVE, CANCELLED, EXPIRED
    current_period_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    current_period_end TIMESTAMP NOT NULL,
    payment_method VARCHAR(64), -- STRIPE, CRYPTO_USDT, VIETQR, PAYPAL
    auto_renew INTEGER DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES saas_users(id) ON DELETE CASCADE
);

-- 3. License Keys & Inventory
CREATE TABLE IF NOT EXISTS saas_licenses (
    license_key VARCHAR(64) PRIMARY KEY, -- Format: NEXTAI-PRO-XXXX-XXXX-XXXX
    plan_code VARCHAR(64) NOT NULL,
    duration_days INTEGER DEFAULT 30,
    max_pc INTEGER DEFAULT 1,
    max_mobile INTEGER DEFAULT 1,
    is_activated INTEGER DEFAULT 0,
    activated_by_user_id VARCHAR(64),
    activated_at TIMESTAMP,
    expires_at TIMESTAMP,
    reseller_id VARCHAR(64), -- If generated by a Reseller
    batch_tag VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. User Devices & Hardware Fingerprint (HWID Binding)
-- BẢNG RÀNG BUỘC PHẦN CỨNG 1 PC + 1 MOBILE CHỐNG CHIA SẺ LẬU
CREATE TABLE IF NOT EXISTS saas_user_devices (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    license_key VARCHAR(64),
    device_type VARCHAR(16) NOT NULL, -- 'PC' OR 'MOBILE'
    device_hwid VARCHAR(128) NOT NULL, -- SHA256 Hardware Fingerprint (CPU+MB+BIOS+MAC / AndroidID)
    device_name VARCHAR(128) NOT NULL, -- E.g. 'DESKTOP-WIN11-OFFICE', 'iPhone 15 Pro Max'
    os_name VARCHAR(64), -- E.g. 'Windows 11 Pro 23H2', 'Android 14', 'iOS 17.5'
    app_version VARCHAR(32) DEFAULT '8.0.0',
    last_ip VARCHAR(64),
    last_geo_location VARCHAR(128),
    last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active INTEGER DEFAULT 1, -- 1 = Authorized, 0 = Deauthorized/Kicked
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES saas_users(id) ON DELETE CASCADE
);

-- Unique constraint: Ensure an HWID is tracked per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_hwid ON saas_user_devices(user_id, device_hwid);

-- 5. Transactions Ledger & Invoices
CREATE TABLE IF NOT EXISTS saas_transactions (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    invoice_number VARCHAR(64) UNIQUE NOT NULL, -- Format: INV-202609-XXXX
    amount_usd REAL NOT NULL,
    amount_vnd REAL,
    gateway VARCHAR(64) NOT NULL, -- STRIPE, CRYPTO_USDT, VIETQR, PAYPAL
    gateway_txn_id VARCHAR(128),
    plan_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) DEFAULT 'PENDING', -- PENDING, COMPLETED, FAILED, REFUNDED
    crypto_wallet VARCHAR(128),
    crypto_tx_hash VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

-- 6. Reseller Network (Đại lý bán sỉ Key & Băng thông)
CREATE TABLE IF NOT EXISTS saas_resellers (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    reseller_code VARCHAR(64) UNIQUE NOT NULL, -- E.g. 'RESELLER_ASIA_01'
    company_name VARCHAR(128),
    tier VARCHAR(32) DEFAULT 'GOLD', -- SILVER (30% off), GOLD (45% off), PLATINUM (55% off)
    discount_rate REAL DEFAULT 0.45,
    wallet_balance_usd REAL DEFAULT 0,
    total_keys_purchased INTEGER DEFAULT 0,
    total_spent_usd REAL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES saas_users(id)
);

-- 7. Affiliate Network (Tiếp thị liên kết & Hoa hồng)
CREATE TABLE IF NOT EXISTS saas_affiliates (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    referral_code VARCHAR(64) UNIQUE NOT NULL, -- E.g. 'boluc2026', 'nextvpn_pro'
    commission_rate REAL DEFAULT 0.25, -- 25% Lifetime Recurring Commission
    unpaid_earnings_usd REAL DEFAULT 0,
    total_paid_usd REAL DEFAULT 0,
    total_clicks INTEGER DEFAULT 0,
    total_signups INTEGER DEFAULT 0,
    total_conversions INTEGER DEFAULT 0,
    payout_method VARCHAR(64) DEFAULT 'USDT_TRC20', -- USDT_TRC20, BANK_TRANSFER, PAYPAL
    payout_address VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES saas_users(id)
);

-- 8. Payout Requests (Yêu cầu rút tiền hoa hồng)
CREATE TABLE IF NOT EXISTS saas_payout_requests (
    id VARCHAR(64) PRIMARY KEY,
    affiliate_id VARCHAR(64) NOT NULL,
    amount_usd REAL NOT NULL,
    payout_method VARCHAR(64) NOT NULL,
    payout_address VARCHAR(128) NOT NULL,
    status VARCHAR(32) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, PAID
    admin_note TEXT,
    tx_hash VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    FOREIGN KEY (affiliate_id) REFERENCES saas_affiliates(id)
);

-- 9. Security, Anti-Fraud & Audit Logs
CREATE TABLE IF NOT EXISTS saas_audit_logs (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64),
    actor_email VARCHAR(255),
    event_type VARCHAR(64) NOT NULL, -- 'DEVICE_ACTIVATED', 'DEVICE_KICKED', 'LIMIT_EXCEEDED_ATTEMPT', 'MULTI_GEO_ALERT', 'KEY_REDEEMED', 'PAYMENT_SUCCESS', 'PROXY_EXHAUSTED_SWITCH'
    severity VARCHAR(16) DEFAULT 'INFO', -- INFO, WARNING, CRITICAL, FRAUD
    ip_address VARCHAR(64),
    geo_location VARCHAR(128),
    user_agent TEXT,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Intermediate Relay Nodes (Dàn VPS Trung Chuyển Phân Tán)
CREATE TABLE IF NOT EXISTS relay_nodes (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    ip VARCHAR(64) NOT NULL,
    port INTEGER DEFAULT 10000,
    country VARCHAR(8) NOT NULL,
    country_name VARCHAR(64),
    region VARCHAR(32) DEFAULT 'Asia', -- Asia, Europe, Americas
    weight INTEGER DEFAULT 100, -- 1 - 100
    active_streams INTEGER DEFAULT 0,
    max_streams INTEGER DEFAULT 5000,
    ping_ms INTEGER DEFAULT 20,
    status VARCHAR(16) DEFAULT 'ONLINE', -- ONLINE, DEGRADED, OFFLINE
    is_enabled INTEGER DEFAULT 1,
    total_bytes_relayed BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. Upstream Proxies with Tiering & 10GB/300MB Quotas
CREATE TABLE IF NOT EXISTS upstream_proxies (
    id VARCHAR(64) PRIMARY KEY,
    type VARCHAR(16) DEFAULT 'socks5', -- socks5, http
    host VARCHAR(128) NOT NULL,
    port INTEGER NOT NULL,
    username VARCHAR(128),
    password VARCHAR(128),
    country VARCHAR(8) DEFAULT 'VN',
    country_name VARCHAR(64) DEFAULT 'Vietnam',
    city VARCHAR(64) DEFAULT 'Hanoi',
    isp VARCHAR(128) DEFAULT 'Residential ISP',
    ping_ms INTEGER,
    status VARCHAR(16) DEFAULT 'LIVE', -- LIVE, OFFLINE, UNCHECKED
    tier VARCHAR(16) DEFAULT 'Vip', -- Free (No-Pass/Slow), Vip (Auth/Fast)
    has_auth INTEGER DEFAULT 0,
    monthly_quota_bytes BIGINT DEFAULT 10737418240, -- 10 GB
    daily_quota_bytes BIGINT DEFAULT 314572800, -- 300 MB
    used_daily_bytes BIGINT DEFAULT 0,
    used_monthly_bytes BIGINT DEFAULT 0,
    daily_reset_date VARCHAR(16),
    is_exhausted_today INTEGER DEFAULT 0,
    auto_switched_count INTEGER DEFAULT 0,
    is_active_vpn INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

