<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="FastVPN">
      <HintPath>E:\DECOMPILER\Soft\VPN\CONVERT\apps\desktop\NextAiVPN_Bypass\FastVPN.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
