<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VpnSDK.Private.WFP</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>extracted/PFiles64/FastVPN/Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>extracted/PFiles64/FastVPN/Serilog.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Extensions.Logging">
      <HintPath>extracted/PFiles64/FastVPN/Serilog.Extensions.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Sinks.File">
      <HintPath>extracted/PFiles64/FastVPN/Serilog.Sinks.File.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>extracted/PFiles64/FastVPN/Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>